### ISSUE TITLE
Plugin doesn't work in UE5.4

### ISSUE THREAD

**Issue by richardboegli** [philspaz/AfootLyraExtension#5]
Hi,

Just loaded up UE5.4 and plugin doesn't load.

Thanks.

**Comment by philspaz** [comment]
Did you put the plugin in the /plugin or in /plugin/gamefeatures? It's working for me in 5.4 but you have to put it in the game features folder alongside the lyra stuff

**Comment by richardboegli** [comment]
I've tried two locations:

I've tried here (Plugins\GameFeatures)
![image](https://github.com/philspaz/AfootLyraExtension/assets/15213383/9b48429d-0961-4599-93f7-a884d3b0a996)

and here: (Plugins)
![image](https://github.com/philspaz/AfootLyraExtension/assets/15213383/c69ecdf4-bda2-4aa5-a36c-ff5682c0b6b3)

They both show the same as being loaded in UE.

![image](https://github.com/philspaz/AfootLyraExtension/assets/15213383/1682f69e-4dca-42b5-864a-f5855db42bea)

**Comment by philspaz** [comment]
Did you open the map in the plugin?

**Comment by richardboegli** [comment]
No.... It works now.

Thanks @philspaz 

First time I've picked up UE and Lyra in a really long time.

Thanks.
